---
- name: Install Dropbox
  become: yes
  dnf: 
    name: https://www.dropbox.com/download?dl=packages/fedora/nautilus-dropbox-2015.10.28-1.fedora.x86_64.rpm
    state: present
  when: ansible_distribution == "Fedora"